name: "Terraform common setup"
description: "Checkout, AWS credentials, Terraform setup + init"

inputs:
  aws-region:
    description: "AWS region"
    required: true
  tf-working-dir:
    description: "Katalog z Terraformem"
    required: true
  role-arn:
    description: "IAM role do konfiguracji AWS"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      working-directory: ${{ inputs.tf-working-dir }}
      shell: bash
      run: terraform init
